# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  voucherpool-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: voucherpool-mysql
    volumes:
      - voucherpool-mysql-data:/var/lib/mysql
    ports:
      - "3336:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=voucherpool
      - MYSQL_DATABASE=voucherpool
      - MYSQL_USER=voucherpool
      - MYSQL_PASSWORD=voucherpool

  # PHP (with nginx)
  app:
    image: ambientum/php:7.0-nginx
    container_name: voucherpool-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql
